### PR TITLE
Add `go_package` option to all proto files

### LINKED ISSUE #8: Add `go_package` option to all files
`protoc` is giving these warnings about it:

```
2020/09/07 14:36:55 WARNING: Missing 'go_package' option in "echo.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
```

Meaning we should update this before the compiler updates to make it mandatory.

### PR DESCRIPTION
**Pull request by jules**
Fixes #8 

Should be merged AFTER #9

### CODE REVIEW

**Review by CPerezz — APPROVED** [review]
LGTM.
@ZER0 any concerns about having this here?

**Comment by ZER0** [comment]
> LGTM.
> @ZER0 any concerns about having this here?

Not at all, it's the only way for go to handle the protobuff schema. The only question is about the naming, we can discuss during the stand up, in the Q&A.

**Comment by jules** [comment]
@ZER0 It turns out that `protoc` uses the `go_package` option to determine the output path. Therefore, I think it's fine to simply have one folder name, called `autogen`. That way, when a project needs to generate structures based off this schema, it can be automated via a `make` command, and the files will then be generated into an `autogen` folder automatically.

**Comment by ZER0** [comment]
> @ZER0 It turns out that `protoc` uses the `go_package` option to determine the output path.

I think this is the default behavior but it can be overridden by the flags set in `protoc`, see: https://github.com/golang/protobuf/issues/464#issuecomment-370960451

I think that would be the sensible option here, and just have a generic enough `go_package` and set the actual path from the `dusk-protobuf`'s Makefile.
Something like `github.com/dusk-network/rusk-schema/` etc. should works.

> Therefore, I think it's fine to simply have one folder name, called `autogen`.

AFAIU you need the _"the full Go package path"_, also this is too generic as `go package` name.

**Comment by jules** [comment]
Good point, I had not considered that. I will change the package path.

**Pull request merged**
